# Generated by Django 5.1.4 on 2025-01-29 04:41

import cloudinary.models
import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaoSat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('ngay_han', models.DateField(null=True)),
                ('ten_khao_sat', models.CharField(default='Khao sat', max_length=255)),
            ],
            options={
                'verbose_name': 'Khảo sát',
                'verbose_name_plural': 'Khảo sát',
            },
        ),
        migrations.CreateModel(
            name='PhiCacDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('ten_dich_vu', models.CharField(default='KHÁC', max_length=255)),
                ('noi_dung', models.TextField()),
                ('phi_dong', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Các chi phí cho phiếu đóng tiền',
                'verbose_name_plural': 'Các chi phí cho phiếu đóng tiền',
            },
        ),
        migrations.CreateModel(
            name='ThongTinChuyenTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('ngan_hang', models.CharField(default='KHÁC', max_length=255)),
                ('so_tai_khoang', models.CharField(default='---', max_length=20)),
                ('ten', models.CharField(default='TÊN', max_length=255)),
            ],
            options={
                'verbose_name': 'Thông tin chuyển tiền',
                'verbose_name_plural': 'Thông tin chuyển tiền',
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('sdt', models.CharField(max_length=10)),
                ('cccd', models.CharField(max_length=12)),
                ('birthdate', models.DateField(default=django.utils.timezone.now)),
                ('thong_bao', models.BooleanField(default=False, verbose_name='Thông báo đơn hàng')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Tài khoảng',
                'verbose_name_plural': 'Tài khoảng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietKhaoSat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('noi_dung', models.TextField(default='cau hoi ?')),
                ('khao_sat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_khao_sat', to='quanlychungcu.khaosat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhanAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('noi_dung', models.TextField()),
                ('tieu_de', models.TextField()),
                ('status', models.CharField(choices=[('waiting', 'Đang chờ xử lý'), ('processed', 'Đã xử lý')], default='waiting', max_length=255)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phan_anhs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HinhAnhPhanAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('phan_anh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anh_phan_anhs', to='quanlychungcu.phananh')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhieuDongTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('screenshot_xac_nhan', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='WAITING', max_length=20)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiếu Đóng Tiền',
                'verbose_name_plural': 'Phiếu Đóng Tiền',
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuDongTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('ten_dich_vu', models.CharField(default='KHÁC', max_length=255)),
                ('noi_dung', models.TextField()),
                ('phi_dong', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitiet_phieudongtiens', to='quanlychungcu.phieudongtien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('so_phong', models.CharField(max_length=255, unique=True)),
                ('nguoi_dung', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phong', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': 'Phòng',
            },
        ),
        migrations.CreateModel(
            name='TheGiuXeNguoiThan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('so_xe', models.CharField(max_length=255)),
                ('ten_nguoi_than', models.CharField(max_length=255)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thẻ giữ xe cho người thân',
                'verbose_name_plural': 'Thẻ giữ xe cho người thân',
            },
        ),
        migrations.CreateModel(
            name='TraLoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('tra_loi', models.CharField(max_length=20)),
                ('chi_tiet_khao_sat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tra_loi', to='quanlychungcu.chitietkhaosat')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TuDoDienTu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 11, 41, 16, 458856))),
                ('ten_do', models.CharField(max_length=255)),
                ('mo_ta', models.CharField(max_length=255)),
                ('ngay_nhan_hang', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('empty', 'Trống'), ('stocked', 'Có hàng')], default='empty', max_length=50, verbose_name='Trạng thái')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tu_dos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
