# Generated by Django 5.1.4 on 2025-01-03 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2025, 1, 3, 11, 38, 14, 271505)),
        ),
    ]
