# Generated by Django 5.1.4 on 2025-01-03 05:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0002_nguoidung_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='phong',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='quanlychungcu.phong'),
        ),
    ]
