# Generated by Django 5.1.4 on 2025-01-03 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0003_alter_nguoidung_birthdate_alter_nguoidung_phong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='phong',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quanlychungcu.phong'),
        ),
    ]
