# Generated by Django 5.1.4 on 2025-01-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0004_alter_nguoidung_phong'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhiCacDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('ten_dich_vu', models.CharField(default='KHÁC', max_length=255)),
                ('noi_dung', models.TextField()),
                ('phi_dong', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chitietphieudongtien',
            name='ten_dich_vu',
            field=models.CharField(default='KHÁC', max_length=255),
        ),
    ]
