# Generated by Django 5.1.4 on 2025-01-10 03:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0005_phicacdichvu_chitietphieudongtien_ten_dich_vu'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieudongtien',
            name='screenshot_xac_nhan',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
