# Generated by Django 5.1.4 on 2025-01-10 04:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0006_phieudongtien_screenshot_xac_nhan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nguoidung',
            options={'verbose_name': 'Tài khoảng', 'verbose_name_plural': 'Tài khoảng'},
        ),
        migrations.AlterModelOptions(
            name='phicacdichvu',
            options={'verbose_name': 'Các chi phí cho phiếu đóng tiền', 'verbose_name_plural': 'Các chi phí cho phiếu đóng tiền'},
        ),
        migrations.AlterModelOptions(
            name='phong',
            options={'verbose_name': 'Phòng', 'verbose_name_plural': 'Phòng'},
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
