# Generated by Django 5.1.4 on 2025-01-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0007_alter_nguoidung_options_alter_phicacdichvu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongTinChuyenTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('ngan_hang', models.CharField(default='KHÁC', max_length=255)),
                ('so_tai_khoang', models.CharField(default='---', max_length=20)),
                ('ten', models.CharField(default='TÊN', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
