# Generated by Django 5.1.4 on 2025-01-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0008_thongtinchuyentien'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phieudongtien',
            options={'verbose_name': 'Phiếu Đóng Tiền', 'verbose_name_plural': 'Phiếu Đóng Tiền'},
        ),
        migrations.AlterModelOptions(
            name='thongtinchuyentien',
            options={'verbose_name': 'Thông tin chuyển tiền', 'verbose_name_plural': 'Thông tin chuyển tiền'},
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='WAITING', max_length=20),
        ),
    ]
