# Generated by Django 5.1.4 on 2025-01-15 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0009_alter_phieudongtien_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thegiuxenguoithan',
            options={'verbose_name': 'Thẻ giữ xe cho người thân', 'verbose_name_plural': 'Thẻ giữ xe cho người thân'},
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='cccd',
            field=models.CharField(default=111111111111, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='luachon',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='luachon',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='traloi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='traloi',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 43, 6, 820980)),
        ),
    ]
