# Generated by Django 5.1.4 on 2025-01-16 07:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0010_alter_thegiuxenguoithan_options_nguoidung_cccd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiDungChiTietKhaoSat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471))),
                ('noi_dung', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chitietkhaosat',
            name='lua_chon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_khao_sats', to='quanlychungcu.luachon'),
        ),
        migrations.AddField(
            model_name='hinhanhphananh',
            name='phan_anh',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anhs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phananh',
            name='nguoi_dung',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phan_anhs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='khao_sat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khao_sats', to='quanlychungcu.khaosat'),
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='phieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitiet_phieudongtiens', to='quanlychungcu.phieudongtien'),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='luachon',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='luachon',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tu_dos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 16, 35, 925471)),
        ),
        migrations.DeleteModel(
            name='TraLoi',
        ),
    ]
