# Generated by Django 5.1.4 on 2025-01-28 03:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0013_alter_noidungchitietkhaosat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='luachon',
            options={'verbose_name': 'Lựa chọn', 'verbose_name_plural': 'Lựa chọn'},
        ),
        migrations.AddField(
            model_name='chitietkhaosat',
            name='nguoi_dung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='lua_chon',
            field=models.TextField(default='###'),
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='luachon',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='luachon',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='noidungchitietkhaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='noidungchitietkhaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 10, 32, 24, 761017)),
        ),
    ]
