# Generated by Django 5.1.4 on 2025-01-28 05:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0014_alter_luachon_options_chitietkhaosat_nguoi_dung_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraLoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823))),
                ('tra_loi', models.CharField(choices=[('Đồng ý', 'Dong Y'), ('Bình thường', 'Binh Thuong'), ('Không đồng ý', 'Khong Dong Y')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LuaChon',
        ),
        migrations.DeleteModel(
            name='NoiDungChiTietKhaoSat',
        ),
        migrations.AlterModelOptions(
            name='khaosat',
            options={'verbose_name': 'Khảo sát', 'verbose_name_plural': 'Khảo sát'},
        ),
        migrations.RemoveField(
            model_name='chitietkhaosat',
            name='lua_chon',
        ),
        migrations.RemoveField(
            model_name='chitietkhaosat',
            name='nguoi_dung',
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='khao_sat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_khao_sat', to='quanlychungcu.khaosat'),
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='noi_dung',
            field=models.TextField(default='cau hoi ?'),
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 56, 34, 147823)),
        ),
        migrations.AddField(
            model_name='traloi',
            name='chi_tiet_khao_sat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tra_loi', to='quanlychungcu.chitietkhaosat'),
        ),
        migrations.AddField(
            model_name='traloi',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
