# Generated by Django 5.1.4 on 2025-01-28 06:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0016_alter_chitietkhaosat_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='traloi',
            name='chi_tiet_khao_sat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tra_loi', to='quanlychungcu.chitietkhaosat'),
        ),
        migrations.AlterField(
            model_name='traloi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='traloi',
            name='nguoi_dung',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traloi',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 13, 29, 34, 508904)),
        ),
    ]
