# Generated by Django 5.1.4 on 2025-01-28 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0019_alter_chitietkhaosat_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='traloi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='traloi',
            name='tra_loi',
            field=models.CharField(default='bruh', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traloi',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 15, 24, 43, 266678)),
        ),
    ]
