# Generated by Django 5.1.4 on 2025-01-27 08:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0019_tudodientu_ngay_nhan_hang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khaosat',
            name='ten_khao_sat',
            field=models.CharField(default='KhaoSat', max_length=255),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='noidungchitietkhaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='noidungchitietkhaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209)),
        ),
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209))),
                ('noi_dung_cau_hoi', models.CharField(max_length=255)),
                ('cau_tra_loi', models.CharField(choices=[('A', 'Rất hài lòng'), ('B', 'Hài lòng'), ('C', 'Bình thường'), ('D', 'Không hài lòng')], default='Bình thường', max_length=50, verbose_name='Đáp án')),
                ('khaosat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hois', to='quanlychungcu.khaosat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThucHienKhaoSat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 43, 11, 619209))),
                ('noi_dung', models.TextField()),
                ('khao_sat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khao_sats', to='quanlychungcu.khaosat')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nguoi_dung_khao_sats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ChiTietKhaoSat',
        ),
        migrations.DeleteModel(
            name='LuaChon',
        ),
    ]
