# Generated by Django 5.1.4 on 2025-01-27 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0020_khaosat_ten_khao_sat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoiDungChiTietKhaoSat',
        ),
        migrations.AlterModelOptions(
            name='nguoidung',
            options={'verbose_name': 'Tài khoản', 'verbose_name_plural': 'Tài khoản'},
        ),
        migrations.RemoveField(
            model_name='khaosat',
            name='active',
        ),
        migrations.RemoveField(
            model_name='khaosat',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='khaosat',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='ngay_han',
            field=models.DateTimeField(null=True, verbose_name='Hạn chót khảo sát'),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='ten_khao_sat',
            field=models.CharField(default='KhaoSat', max_length=255, verbose_name='Tên khảo sát'),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='thuchienkhaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='thuchienkhaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 18, 3, 132151)),
        ),
    ]
