# Generated by Django 5.1.4 on 2025-01-27 09:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0021_delete_noidungchitietkhaosat_alter_nguoidung_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cauhoi',
            name='cau_tra_loi',
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='khaosat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hois', to='quanlychungcu.khaosat', verbose_name='Khảo sát'),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='thuchienkhaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='thuchienkhaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 24, 44, 493291)),
        ),
    ]
