# Generated by Django 5.1.4 on 2025-01-28 15:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0021_nguoidung_thong_bao_tudodientu_ngay_nhan_hang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='chitietkhaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='phan_anh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anh_phan_anhs', to='quanlychungcu.phananh'),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='traloi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='traloi',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 2, 52, 488557)),
        ),
    ]
