# Generated by Django 5.1.4 on 2025-01-27 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0023_alter_cauhoi_created_date_alter_cauhoi_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhoi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='thuchienkhaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='thuchienkhaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 16, 36, 56, 741492)),
        ),
    ]
