# Generated by Django 5.1.4 on 2025-01-27 11:50

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlychungcu', '0024_alter_cauhoi_created_date_alter_cauhoi_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhoi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='noi_dung_cau_hoi',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='chitietphieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='hinhanhphananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='phicacdichvu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='phieudongtien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='thegiuxenguoithan',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='thongtinchuyentien',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='thuchienkhaosat',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='thuchienkhaosat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='mo_ta',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tudodientu',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 50, 51, 50050)),
        ),
    ]
